clone:
    hg:
        image: plugins/hg
        environment:
            - HG_SHARE_POOL=/root/.cache/hg
        volumes:
            - cache:/root/.cache

pipeline:
    npm:
        image: tryton/sao-test
        commands:
            - sh .bower_allow_root.sh
            - npm -s install --unsafe-perm --legacy-peer-deps
            - npm test
        volumes:
            - cache-npm:/root/.npm
